# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bca9972e46d56cdf3cc684ff259ec9a4f7ed8f9c05ef1550f6333e323aa5e808f4feb24a44d25d59edfa159c6159d73b2ef92910e6c27318b06d5155a9eda094

test:
  secret_key_base: 0525cd7cf3f0bfba2f7ba455b9eb587613453b4fc95f1d7c4ec4be41486ff85dc2321100d1d8195313755185a0eff1db99cd186e9fb8af4b021e2c902628de16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
